# Generated by Django 6.0.6 on 2026-07-21 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque public session identifier. Exposed to clients instead of internal DB surrogate keys.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOGGED_OUT", "Logged Out"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Current lifecycle state of the session.",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address at login time. Extracted from X-Forwarded-For or REMOTE_ADDR. Used for impossible-travel and suspicious login detection.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Raw User-Agent header string captured at login time.",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("MOBILE", "Mobile"),
                            ("TABLET", "Tablet"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Broad device category derived from User-Agent (Desktop / Mobile / Tablet / Unknown).",
                        max_length=16,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Browser name and major version parsed from User-Agent (e.g. 'Chrome 124').",
                        max_length=128,
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Operating system name parsed from User-Agent (e.g. 'Windows 11', 'iOS 17').",
                        max_length=128,
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when this session was established (user authenticated successfully).",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Timestamp of the most recent authenticated request in this session. Updated by the session middleware on every valid API call. Used for sliding expiry and suspicious activity detection.",
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user explicitly logged out. Null until a voluntary logout occurs. Must be non-null when status is LOGGED_OUT.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Hard expiry timestamp for this session, aligned with the JWT refresh token lifetime. Sessions are considered EXPIRED after this point regardless of activity.",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when an administrator forcibly revoked this session. Must be non-null when status is REVOKED.",
                        null=True,
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable explanation for why the session was forcibly terminated. Required for compliance audit trails when revoked by an administrator.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization context for the session. Null for platform-level (non-tenant) sessions. Supports future concurrent-session limits per tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_sessions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who revoked this session. Null for self-revocation (logout) or TTL expiry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The authenticated user this session belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_sessions",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_usess_user"),
                    models.Index(fields=["organization"], name="idx_usess_org"),
                    models.Index(fields=["status"], name="idx_usess_status"),
                    models.Index(fields=["expires_at"], name="idx_usess_expires_at"),
                    models.Index(
                        fields=["last_activity"], name="idx_usess_last_activity"
                    ),
                    models.Index(
                        fields=["user", "status"], name="idx_usess_user_status"
                    ),
                    models.Index(
                        fields=["organization", "status"], name="idx_usess_org_status"
                    ),
                    models.Index(
                        fields=["status", "expires_at"], name="idx_usess_status_expires"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("logout_time__isnull", True),
                            ("status", "LOGGED_OUT"),
                            _connector="OR",
                        ),
                        name="chk_usess_logout_time_requires_logged_out",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True),
                            ("status", "REVOKED"),
                            _connector="OR",
                        ),
                        name="chk_usess_revoked_at_requires_revoked",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("last_activity__gte", models.F("login_time"))
                        ),
                        name="chk_usess_last_activity_not_before_login",
                    ),
                ],
            },
        ),
    ]
