# Generated by Django 6.0.6 on 2026-07-22 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template slug identifier, e.g. verification_email, login_alert.",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SECURITY", "Security"),
                            ("AUTHENTICATION", "Authentication"),
                            ("MFA", "Multi-Factor Authentication"),
                            ("ORGANIZATION", "Organization"),
                            ("ACCOUNT", "Account"),
                            ("SYSTEM", "System"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject line template.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="In-app or header title template.", max_length=255
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Body content template supporting Django template syntax placeholders."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this template is available for message rendering.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "channel"),
                "indexes": [
                    models.Index(
                        fields=["name", "channel"], name="notificatio_name_3d0da1_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="notificatio_is_acti_b2a982_idx"
                    ),
                ],
                "unique_together": {("name", "channel")},
            },
        ),
    ]
