"""
Password reset email service for the SecureAuthX authentication module.

Sends a professional enterprise-grade HTML email with a plain-text fallback
containing a secure password reset link.
"""

from django.conf import settings
from django.core.mail import EmailMultiAlternatives


class PasswordResetEmailService:
    """
    Responsible for composing and dispatching password reset emails.
    """

    SUBJECT = "Reset Your SecureAuthX Password"

    @classmethod
    def send(cls, user, token: str) -> None:
        """
        Send a password reset email to the user.

        The email contains an HTML version and a plain-text fallback.
        The reset link embeds the signed token as a query parameter so
        the frontend can extract it and call ``POST /api/v1/auth/reset-password/``.

        Args:
            user:  The User instance requesting the password reset.
            token: Signed password reset token generated by ``TokenService``.
        """

        reset_url = cls._build_reset_url(token)
        plain_text = cls._render_plain_text(user, reset_url)
        html_body = cls._render_html(user, reset_url)

        message = EmailMultiAlternatives(
            subject=cls.SUBJECT,
            body=plain_text,
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=[user.email],
        )

        message.attach_alternative(html_body, "text/html")
        message.send(fail_silently=False)

    # --------------------------------------------------------------------------
    # Private helpers
    # --------------------------------------------------------------------------

    @staticmethod
    def _build_reset_url(token: str) -> str:
        """
        Build the full password reset URL with the token embedded.

        Falls back to ``http://localhost:3000`` when ``FRONTEND_URL``
        is not set in the environment.
        """

        frontend_url = getattr(settings, "FRONTEND_URL", "http://localhost:3000")
        return f"{frontend_url}/reset-password?token={token}"

    @staticmethod
    def _render_plain_text(user, reset_url: str) -> str:
        """
        Compose the plain-text email body.
        """

        display_name = user.full_name or user.email

        return (
            f"Hi {display_name},\n\n"
            "We received a request to reset the password for your SecureAuthX account.\n\n"
            f"Reset your password by visiting the link below:\n{reset_url}\n\n"
            "This link will expire in 30 minutes.\n\n"
            "If you did not request a password reset, you can safely ignore this email. "
            "Your password will not be changed.\n\n"
            "For security, never share this link with anyone.\n\n"
            "— The SecureAuthX Team"
        )

    @staticmethod
    def _render_html(user, reset_url: str) -> str:
        """
        Compose the HTML email body.

        Uses an inline-styled, responsive layout compatible with
        all major email clients.
        """

        display_name = user.full_name or user.email

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reset Your Password</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f6f9;font-family:'Segoe UI',Arial,sans-serif;">

  <!-- Wrapper -->
  <table width="100%" cellpadding="0" cellspacing="0" border="0"
         style="background-color:#f4f6f9;padding:40px 0;">
    <tr>
      <td align="center">

        <!-- Card -->
        <table width="600" cellpadding="0" cellspacing="0" border="0"
               style="background-color:#ffffff;border-radius:8px;
                      box-shadow:0 2px 8px rgba(0,0,0,0.08);overflow:hidden;
                      max-width:600px;width:100%;">

          <!-- Header -->
          <tr>
            <td style="background-color:#1a1a2e;padding:32px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:700;
                         letter-spacing:1px;">
                🔐 SecureAuthX
              </h1>
              <p style="margin:8px 0 0;color:#a0aec0;font-size:13px;">
                Enterprise Identity &amp; Access Management
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:40px 40px 32px;">

              <h2 style="margin:0 0 16px;color:#1a202c;font-size:20px;font-weight:600;">
                Password Reset Request
              </h2>

              <p style="margin:0 0 16px;color:#4a5568;font-size:15px;line-height:1.6;">
                Hi <strong>{display_name}</strong>,
              </p>

              <p style="margin:0 0 16px;color:#4a5568;font-size:15px;line-height:1.6;">
                We received a request to reset the password associated with your
                SecureAuthX account. Click the button below to set a new password.
              </p>

              <!-- CTA Button -->
              <table cellpadding="0" cellspacing="0" border="0"
                     style="margin:32px auto;">
                <tr>
                  <td align="center"
                      style="background-color:#4f46e5;border-radius:6px;">
                    <a href="{reset_url}"
                       style="display:inline-block;padding:14px 36px;
                              color:#ffffff;font-size:15px;font-weight:600;
                              text-decoration:none;letter-spacing:0.3px;">
                      Reset My Password
                    </a>
                  </td>
                </tr>
              </table>

              <!-- Expiry notice -->
              <p style="margin:0 0 16px;color:#718096;font-size:13px;
                        background-color:#fffbeb;border:1px solid #f6e05e;
                        border-radius:6px;padding:12px 16px;">
                ⏱️ <strong>This link expires in 30 minutes.</strong>
              </p>

              <!-- Fallback URL -->
              <p style="margin:0 0 8px;color:#718096;font-size:13px;line-height:1.6;">
                If the button above does not work, copy and paste the following
                URL into your browser:
              </p>
              <p style="margin:0 0 24px;word-break:break-all;">
                <a href="{reset_url}"
                   style="color:#4f46e5;font-size:13px;">{reset_url}</a>
              </p>

              <!-- Did not request -->
              <p style="margin:0;color:#718096;font-size:13px;line-height:1.6;
                        border-top:1px solid #e2e8f0;padding-top:24px;">
                If you did not request a password reset, no action is needed —
                your password will remain unchanged. Never share this link with
                anyone, including SecureAuthX support.
              </p>

            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color:#f7fafc;padding:20px 40px;
                       border-top:1px solid #e2e8f0;text-align:center;">
              <p style="margin:0;color:#a0aec0;font-size:12px;">
                © 2025 SecureAuthX. All rights reserved.
              </p>
              <p style="margin:6px 0 0;color:#a0aec0;font-size:12px;">
                This is an automated message — please do not reply to this email.
              </p>
            </td>
          </tr>

        </table>
        <!-- /Card -->

      </td>
    </tr>
  </table>
  <!-- /Wrapper -->

</body>
</html>"""
