# Generated by Django 6.0.6 on 2026-07-22 17:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Hashed password string.", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password Histories",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="security_po_user_id_e96c32_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive policy identifier, e.g. 'Global Security Policy' or 'Acme Corp Policy'.",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this policy is actively enforced.",
                    ),
                ),
                (
                    "min_password_length",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Minimum character count for user passwords.",
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(128),
                        ],
                    ),
                ),
                (
                    "max_password_length",
                    models.PositiveIntegerField(
                        default=128,
                        help_text="Maximum character length for user passwords.",
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
                (
                    "require_uppercase",
                    models.BooleanField(
                        default=True,
                        help_text="Requires at least one uppercase letter (A-Z).",
                    ),
                ),
                (
                    "require_lowercase",
                    models.BooleanField(
                        default=True,
                        help_text="Requires at least one lowercase letter (a-z).",
                    ),
                ),
                (
                    "require_numeric",
                    models.BooleanField(
                        default=True,
                        help_text="Requires at least one numeric digit (0-9).",
                    ),
                ),
                (
                    "require_special_char",
                    models.BooleanField(
                        default=True,
                        help_text="Requires at least one special character (!@#$%^&*...).",
                    ),
                ),
                (
                    "password_history_count",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of previous password hashes to retain and prevent reuse.",
                        validators=[django.core.validators.MaxValueValidator(24)],
                    ),
                ),
                (
                    "password_expiration_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Days before user password expires and requires change. 0 disables expiration.",
                    ),
                ),
                (
                    "max_failed_login_attempts",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum consecutive failed login attempts before locking account.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "lockout_duration_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Duration in minutes an account remains locked.",
                    ),
                ),
                (
                    "auto_unlock_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, accounts auto-unlock after lockout_duration_minutes expires.",
                    ),
                ),
                (
                    "max_concurrent_sessions",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum active user sessions allowed simultaneously. 0 = unlimited.",
                    ),
                ),
                (
                    "session_absolute_timeout_minutes",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="Maximum absolute session duration in minutes (e.g. 1440 = 24 hours).",
                    ),
                ),
                (
                    "session_idle_timeout_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Maximum inactivity idle time in minutes before session invalidation.",
                    ),
                ),
                (
                    "force_logout_on_password_change",
                    models.BooleanField(
                        default=True,
                        help_text="Revokes all active sessions upon password reset or modification.",
                    ),
                ),
                (
                    "require_mfa_for_admins",
                    models.BooleanField(
                        default=True,
                        help_text="Mandates TOTP MFA for all administrator users.",
                    ),
                ),
                (
                    "require_mfa_for_all_org_members",
                    models.BooleanField(
                        default=False,
                        help_text="Mandates TOTP MFA for all members in the organization.",
                    ),
                ),
                (
                    "mfa_grace_period_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days allowed for new users to configure MFA before access is blocked.",
                    ),
                ),
                (
                    "allowed_login_start_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="UTC start hour (0-23) for permitted logins. Null = unrestricted.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "allowed_login_end_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="UTC end hour (0-23) for permitted logins. Null = unrestricted.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "ip_allowlist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed IP addresses or CIDR blocks, e.g. ['192.168.1.0/24'].",
                    ),
                ),
                (
                    "ip_denylist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of explicitly blocked IP addresses or CIDR blocks.",
                    ),
                ),
                (
                    "country_denylist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of blocked ISO 2-letter country codes, e.g. ['CN', 'RU'].",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated organization for tenant-scoped policies. Null designates global default policy.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_policy",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Policy",
                "verbose_name_plural": "Security Policies",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization"], name="security_po_organiz_0f2b5b_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="security_po_is_acti_ca8e84_idx"
                    ),
                ],
            },
        ),
    ]
