# Generated by Django 5.0.6 on 2026-07-13 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REGISTER", "Register"),
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("EMAIL_VERIFIED", "Email Verified"),
                            ("EMAIL_VERIFICATION_SENT", "Email Verification Sent"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("TOKEN_REFRESHED", "Token Refreshed"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("ORGANIZATION_CREATED", "Organization Created"),
                            ("ORGANIZATION_UPDATED", "Organization Updated"),
                            ("ORGANIZATION_DELETED", "Organization Deleted"),
                            ("ROLE_CREATED", "Role Created"),
                            ("ROLE_UPDATED", "Role Updated"),
                            ("ROLE_DELETED", "Role Deleted"),
                            ("ROLE_ASSIGNED", "Role Assigned"),
                            ("ROLE_REMOVED", "Role Removed"),
                            ("PERMISSION_CREATED", "Permission Created"),
                            ("PERMISSION_UPDATED", "Permission Updated"),
                            ("PERMISSION_DELETED", "Permission Deleted"),
                            ("PERMISSION_ASSIGNED", "Permission Assigned"),
                            ("PERMISSION_REMOVED", "Permission Removed"),
                            ("MFA_ENABLED", "MFA Enabled"),
                            ("MFA_DISABLED", "MFA Disabled"),
                            ("SESSION_CREATED", "Session Created"),
                            ("SESSION_REVOKED", "Session Revoked"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=16,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address extracted from the HTTP request.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Client User-Agent string from the HTTP request.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable summary of what occurred.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary structured context for the event.",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resource type affected by the event (e.g. 'User', 'Role').",
                        max_length=128,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifier of the affected resource.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. Null for unauthenticated events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
