# Generated by Django 5.0.6 on 2026-07-15 13:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this permission capability.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for administrators.",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Machine-readable capability identifier (e.g., identity:user:create).",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_permission_code",
                                message="Permission code must contain only lowercase letters, numbers, underscores, colons, or hyphens.",
                                regex="^[a-z0-9_:-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        db_index=True,
                        help_text="Resource classification namespace (e.g., identity:user, organization, audit:log).",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_resource_namespace",
                                message="Resource namespace must contain only lowercase letters, numbers, underscores, colons, or hyphens.",
                                regex="^[a-z0-9_:-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Standard action verb (e.g., create, read, update, delete, manage, execute).",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_action_verb",
                                message="Action verb must contain only lowercase letters, numbers, underscores, or hyphens.",
                                regex="^[a-z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Details about the scope, security implications, and impact of this capability.",
                        null=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating if this is an immutable system-defined permission.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag for administrative revocation without breaking relations.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the permission was registered.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the permission definition was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "authx_permissions",
                "ordering": ["resource", "action"],
            },
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.UniqueConstraint(
                fields=("resource", "action"), name="unique_resource_action"
            ),
        ),
    ]
