# Generated by Django 5.0.6 on 2026-07-15 15:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this role.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable label for the role (e.g., Administrator, HR Manager).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe, machine-readable unique identifier for the role.",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_role_slug",
                                message="Role slug must contain only lowercase letters, numbers, underscores, or hyphens.",
                                regex="^[a-z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Details about the duties, operational scope, and purpose of this role.",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Precedence ranking for administrative priority and resolution purposes.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating if this is a built-in immutable system role.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag for administrative revocation without deleting database records.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the role was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the role definition was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "authx_roles",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this user-role assignment.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason/justification for allocating this role to the user.",
                        null=True,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the assignment was originally made.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration timestamp for temporary or Just-in-Time (JIT) access grants.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this role membership is currently active.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Audit creation timestamp."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Audit modification timestamp."
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The administrator user who performed the assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="The role assigned to the user.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="role_users",
                        to="authorization.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user receiving the role assignment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "authx_user_roles",
                "ordering": ["user", "role"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this role-permission mapping.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assignment_reason",
                    models.TextField(
                        blank=True,
                        help_text="Justification for this permission assignment, required for compliance.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this specific capability mapping is currently active.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this mapping was established.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this mapping definition was last modified.",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The administrative user who mapped this capability to the role.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        help_text="The permission catalog capability mapped to the role.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="permission_roles",
                        to="authorization.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="The role receiving the capability mapping.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="authorization.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "authx_role_permissions",
                "ordering": ["role", "permission"],
                "indexes": [
                    models.Index(
                        fields=["role", "is_active"], name="idx_role_active_perms"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user"], name="idx_user_role_user"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="idx_user_role_role"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["is_active"], name="idx_user_role_active"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["expires_at"], name="idx_user_role_expires"),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "role"),
                name="unique_active_user_role",
            ),
        ),
    ]
