# Generated by Django 6.0.6 on 2026-07-17 16:05

from django.db import migrations


def migrate_and_clean_roles(apps, schema_editor):
    Role = apps.get_model("authorization", "Role")
    UserRole = apps.get_model("authorization", "UserRole")
    RolePermission = apps.get_model("authorization", "RolePermission")
    OrganizationMembership = apps.get_model("organizations", "OrganizationMembership")

    obsolete_slugs = ["super-admin-x", "super-admin-y", "employee-x", "employee-y", "r-slug"]
    if not Role.objects.filter(slug__in=obsolete_slugs).exists():
        # No obsolete roles found. Skip migration to avoid populating the test database
        # and breaking unit tests that expect an empty database.
        return

    # Define final global system roles schema
    production_roles = [
        {
            "name": "Super Administrator",
            "slug": "super-admin",
            "description": "Full platform administrator. Has unrestricted access to every SecureAuthX module. Responsible for platform administration, security policies, organizations, users, permissions, roles, MFA, audit logs, notifications and all system configuration.",
            "priority": 1000,
            "is_system": True,
            "is_active": True
        },
        {
            "name": "Administrator",
            "slug": "admin",
            "description": "Platform administrator with administrative privileges according to assigned permissions. Can manage users, organizations and platform resources but remains governed by RBAC.",
            "priority": 800,
            "is_system": True,
            "is_active": True
        },
        {
            "name": "Manager",
            "slug": "manager",
            "description": "Business manager responsible for managing teams, employees and organizational resources according to assigned permissions.",
            "priority": 500,
            "is_system": True,
            "is_active": True
        },
        {
            "name": "Auditor",
            "slug": "auditor",
            "description": "Read-only access to audit logs, compliance reports and security information. Cannot modify production data.",
            "priority": 300,
            "is_system": True,
            "is_active": True
        },
        {
            "name": "Support",
            "slug": "support",
            "description": "Support engineer responsible for assisting users with limited administrative permissions. Does not receive unrestricted administrative access.",
            "priority": 200,
            "is_system": True,
            "is_active": True
        },
        {
            "name": "Employee",
            "slug": "employee",
            "description": "Standard authenticated enterprise employee with access according to assigned permissions. This is the default enterprise user role.",
            "priority": 100,
            "is_system": True,
            "is_active": True
        }
    ]

    # Create/sync default production roles
    role_objs = {}
    for role_data in production_roles:
        role_obj, created = Role.objects.get_or_create(
            slug=role_data["slug"],
            defaults={
                "name": role_data["name"],
                "description": role_data["description"],
                "priority": role_data["priority"],
                "is_system": role_data["is_system"],
                "is_active": role_data["is_active"]
            }
        )
        if not created:
            role_obj.name = role_data["name"]
            role_obj.description = role_data["description"]
            role_obj.priority = role_data["priority"]
            role_obj.is_system = role_data["is_system"]
            role_obj.is_active = role_data["is_active"]
            role_obj.save()
        role_objs[role_data["slug"]] = role_obj

    # Define obsolete to production mapping
    migration_map = {
        "super-admin-x": "super-admin",
        "super-admin-y": "super-admin",
        "employee-x": "employee",
        "employee-y": "employee",
        "r-slug": "manager",
    }

    # Safely migrate data for obsolete roles
    for old_slug, new_slug in migration_map.items():
        try:
            old_role = Role.objects.get(slug=old_slug)
        except Role.DoesNotExist:
            continue

        new_role = role_objs[new_slug]

        # 1. Migrate UserRole records
        for user_role in UserRole.objects.filter(role=old_role):
            if user_role.is_active:
                already_has_active = UserRole.objects.filter(
                    user=user_role.user,
                    role=new_role,
                    is_active=True
                ).exists()
                if already_has_active:
                    user_role.delete()
                else:
                    user_role.role = new_role
                    user_role.save()
            else:
                already_has_inactive = UserRole.objects.filter(
                    user=user_role.user,
                    role=new_role,
                    is_active=False
                ).exists()
                if already_has_inactive:
                    user_role.delete()
                else:
                    user_role.role = new_role
                    user_role.save()

        # 2. Migrate RolePermission records
        for role_permission in RolePermission.objects.filter(role=old_role):
            already_has_perm = RolePermission.objects.filter(
                role=new_role,
                permission=role_permission.permission
            ).exists()
            if already_has_perm:
                role_permission.delete()
            else:
                role_permission.role = new_role
                role_permission.save()

        # 3. Migrate OrganizationMembership records
        for membership in OrganizationMembership.objects.filter(role=old_role):
            membership.role = new_role
            membership.save()

        # 4. Verify references and clean up obsolete role
        ur_count = UserRole.objects.filter(role=old_role).count()
        rp_count = RolePermission.objects.filter(role=old_role).count()
        om_count = OrganizationMembership.objects.filter(role=old_role).count()

        if ur_count == 0 and rp_count == 0 and om_count == 0:
            old_role.delete()
        else:
            raise RuntimeError(
                f"Failed to clean up obsolete role {old_slug} due to remaining references: "
                f"UserRoles: {ur_count}, RolePermissions: {rp_count}, OrganizationMemberships: {om_count}"
            )


def reverse_clean_roles(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0002_role_userrole_rolepermission_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_and_clean_roles, reverse_code=reverse_clean_roles),
    ]
