# Generated by Django 6.0.6 on 2026-07-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Account remains locked until this time.",
                null=True,
            ),
        ),
    ]
