# Generated by Django 6.0.6 on 2026-07-21 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "secret",
                    models.TextField(
                        blank=True, default="", help_text="Encrypted TOTP secret."
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_used_time_step",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Last accepted TOTP timestep for replay protection.",
                        null=True,
                    ),
                ),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Device",
                "verbose_name_plural": "MFA Devices",
                "db_table": "mfa_devices",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MFARecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(help_text="Hashed recovery code.", max_length=255),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mfa_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to="mfa.mfadevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Recovery Code",
                "verbose_name_plural": "MFA Recovery Codes",
                "db_table": "mfa_recovery_codes",
                "ordering": ("-created_at",),
            },
        ),
    ]
